### ISSUE TITLE
gcloud sql instances patch errors saying not authorized even when using service account

### ISSUE THREAD

**Issue by rajasharan** [GoogleCloudPlatform/gcloud-common#101]
I'm using gcloud cli on my mac
```
$ gcloud --version
Google Cloud SDK 94.0.0

bq 2.0.18
bq-nix 2.0.18
core 2016.01.22
core-nix 2015.11.24
gcloud
gsutil 4.16
gsutil-nix 4.15
kubectl
kubectl-darwin-x86_64 1.1.4
```

Here are the steps I followed on my mac:
1. I've enabled `Google Cloud SQL API` from the API Manager in web console for my project
2. I've created a new service account and downloaded the json key to my mac
3. Ran the `gcloud auth activate-service-account --key-file <jsonfile>`
4. Checked the account is active: `gcloud auth list`

Now I'm trying to run this command which fails:
```
$ gcloud sql instances patch <my-project> --authorized-networks 104.196.106.27,104.196.6.168
ERROR: (gcloud.sql.instances.patch) The client is not authorized to make this request.
```

Any idea if I'm doing something wrong or is there an easier way to authorize all of my gce/gke instances to automatically be authorized to the SQL instance?

**Comment by blowmage** [comment]
Hi @rajasharan, I don't know much about sql instances, but I wonder if the reason you are getting authorization errors is due to using a service account. What happens if you authenticate as your user account using `$ gcloud auth login`? Do you get the same error?

**Comment by rajasharan** [comment]
Hi @blowmage, I tried with my original owner account as well. It gives the same error.

I do know that the command works if I run it as part of startup script while spinning up the gce instance. So I was hoping service account will work. Maybe startup scripts have additional privileges.

**Comment by blowmage** [comment]
Are you able to use the API in the "Try it!" section at the bottom of the API docs page?

https://cloud.google.com/sql/docs/admin-api/v1beta4/instances/patch#try-it

**Comment by rajasharan** [comment]
oh wow! that API docs page playground worked (my specific use-case property was nested under settings -> ipConfiguration -> authorizedNetworks).

So what does this prove - something wrong with gcloud cli itself?

**Comment by jgeewax** [comment]
@rajasharan Do you have the right project selected? Have you tried with `--project=your-project-id` ?

**Comment by rajasharan** [comment]
Sorry guys my bad - patch requires a SQL_INSTANCE_ID as param instead of PROJECT_ID.
@jgeewax thanks for the pointer (the project-id was already set in the gcloud configuration).
Closing the issue.
