### ISSUE TITLE
Switch "%23{name}" back to "?method={name}"

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-common#113]
Is it possible to remove the "%23" and bring back "?method=" in our URLs?

**Comment by blowmage** [comment]
You can use whatever format you want for the method ID, including using `?method=`. I'm not sure if the ID is URL encoded though.

**Comment by callmehiphop** [comment]
> You can use whatever format you want for the method ID, including using ?method=. I'm not sure if the ID is URL encoded though.

I think formatting a method ID to resemble a URL (query string and all) would be coupling the site & json a little *too* tightly IMO.

I think @quartzmo had initially started down this road, but maybe we just make 2 IDs per method, one global ID and one that's unique to the service. Then use the unique service ID for deeplinking?

**Comment by quartzmo** [comment]
I am perfectly OK with switching (*back*, with an added param) to `?method={name}&type={type}`. I just need a way to support linking methods that have the same name in the same namespace!

Please let me know what to do! I can start work on a new PR to replace #109 immediately.

**Comment by quartzmo** [comment]
@stephenplusplus Are you OK with adding a second "query string" param for code object `type`, in addition to the `method` param?

@callmehiphop What is your preference?

**Comment by blowmage** [comment]
I would prefer to not have two values in the routing. We can remove the `%23` without taking this step.

**Comment by stephenplusplus** [comment]
I'm okay with the query parameter if that helps differentiate between methods, although ideally we can find a solution that works for overloaded methods. If that can all be done in a single "method" property, that seems like the path of least resistance, e.g. `?method=datasetStatic`, `?method=datasetInstance`, `?method=datasetFromString`, etc.

**Comment by quartzmo** [comment]
@stephenplusplus That is in fact the design I offered in PR #100, [using the format](https://github.com/quartzmo/gcloud-common/blob/ba49b3f58ed61efda6ceffaf82e1532b9ab99c87/site/src/app/docs/docs.service.js#L75) `?method=dataset-type-instance`, although I'm not particular in the slightest.

I'm more than happy to do the work provided all stakeholders can come to an agreement on the design.

**Comment by stephenplusplus** [comment]
Thanks for putting the work in and dealing with all of these discussions. On the Node side, we prefer the `?method={id}` system and it sounds like that works for you guys. That sounds like enough :+1:s for moving forward on this type of change, but feel free to pull in anyone else you think might want to weigh in.

**Comment by quartzmo** [comment]
@stephenplusplus So you guys want what @callmehiphop [described above](https://github.com/GoogleCloudPlatform/gcloud-common/issues/113#issuecomment-199442656): 

> 2 IDs per method, one global ID and one that's unique to the service. Then use the unique service ID for deeplinking

With the format: `/{serviceId}?method={serviceScopeId}`

**Comment by stephenplusplus** [comment]
Can we just do something like:

```js
// GET docs/#/json/master/bigquery?method=dataset-type-instance loads:
{
  id: 'dataset-type-instance', // for lookups
  name: 'dataset', // for display
  params: [...]
}
```

**Comment by quartzmo** [comment]
Like I said, I'm OK with any solution that supports linking to methods with the same name that belong to the same namespace.

**Comment by stephenplusplus** [comment]
Then it's time to break out the drinks. JJ's buying.

**Comment by quartzmo** [comment]
@blowmage ?

**Comment by quartzmo** [comment]
I just pushed a [new demo](https://quartzmo.github.io/gcloud-ruby/#/) on the current codebase. This was @blowmage's idea to replace `%23` with `~`. I think it works well and has the advantage of no further code changes.

**Comment by quartzmo** [comment]
@stephenplusplus PTAL! I want to move our docs to the Angular site **tomorrow**. If you don't like the  [new demo](https://quartzmo.github.io/gcloud-ruby/#/) and want to go back to `?method={name}`, I can do a new PR for that today, but everyone including @blowmage needs to be on board.

**Comment by stephenplusplus** [comment]
I still prefer `?method={name}`. It's more URL-schema friendly and understandable. If your docs can function within the constraints of `?method={name}`, then I see no reason to introduce a breaking URL change (I've linked to `?method=` docs links countless times across the web). I think we should revert asap and carry out any discussion about why we should change to another system continue if necessary.

**Comment by blowmage** [comment]
I think that [new demo](https://quartzmo.github.io/gcloud-ruby/#/docs/master/gcloud/bigquery/table~copy) looks way better. I'm super impressed by the speed of navigating across methods as well. By using the `~` the paths aren't URI escaped in the address bar, which solves the problem as far as I'm concerned. I can see how we can build new features like search using this JSON schema. So I'm totally :+1: on this and would love to see the gcloud-ruby docs moved to it.

**Comment by blowmage** [comment]
@stephenplusplus Bummer, we cross posted. I would prefer we stay with what is committed now, and that we not revert. AFAIAC we are code complete on our end and we'd like to push this to production. We've put a lot of work into getting the docs so they work for our needs, and I'd hate to see the rug pulled out from our efforts. But in the end I think this is really your call.

**Comment by callmehiphop** [comment]
I think what @stephenplusplus is trying to get at is that it would be better if we used a somewhat common URL structure for deeplinking and I've always been under the impression that the Angular way of handling this is to use query strings.

I'm inclined to agree that the old way is more desirable, but rather than reverting right now could we just make a post ruby launch action item to get us back on the previous format?

**Comment by quartzmo** [comment]
@stephenplusplus @blowmage @callmehiphop Thanks for the quick responses! I'll let you guys get to a resolution. I'm happy to do whatever.

**Comment by blowmage** [comment]
I totally see the point about not wanting to change the existing URLs. I am very sympathetic to that; I don't like changing URLs either. But all the existing doc URLs for ruby, python, php, etc will change as a result of moving to the angular app. I just don't agree that the cost of maintaining two unique IDs for methods in the JSON is worth the cost. I think it will be confusing down the road for future adopters.

But I'm also fine with you guys deciding to make changes to what we have built to this point. I have one opinion on this, and its okay for you to have a different opinion. But we've put so much time into moving the ruby docs to this and we would really like to move on to other things.

**Comment by callmehiphop** [comment]
@quartzmo please don't hate me for what I'm about to suggest!

I think not wanting to maintain 2 unique IDs is a fair point, so what if we just use a single unique ID to be used at the service level and not a global level. I believe @quartzmo started down this road, and I was confused only because the previous schema proposals called for a globally unique ID (unless I misunderstood, which if so, I apologize).

**Comment by quartzmo** [comment]
@callmehiphop No problem! That's exactly what I understood [from @stephenplusplus' design sketch above](https://github.com/GoogleCloudPlatform/gcloud-common/issues/113#issuecomment-199590996).

**Comment by blowmage** [comment]
We need method IDs to be globally unique so we can link to/from methods across "service levels" (which I assume you mean types). For example, we might want to link from the `CopyJob` type/service to the method `Table#copy`. That's why we need the method ID to be global.

**Comment by blowmage** [comment]
Another example (with links) is where we link from [Gcloud::Bigquery::Project](https://quartzmo.github.io/gcloud-ruby/#/docs/master/gcloud/bigquery/project) to [Gcloud#bigquery](https://quartzmo.github.io/gcloud-ruby/#/docs/master/gcloud~bigquery).

**Comment by callmehiphop** [comment]
I totally see why you want the global ID. I think we could get away with a service level ID if we just changed the `custom-type` directive to optional look for a method name elsewhere.

e.g.

```html
<a data-custom-type="Gcloud" data-method="#bigquery"></a>
```

To me this is ideal because:

1. We maintain the quick lookups from your schema change proposals
2. We can create a globally unique ID without much effort that does not require language specific logic
3. It would be very simple to bring back the `?method={methodId}` syntax

**Comment by blowmage** [comment]
That would work. We know the type of the link (guide, type, method) when we generate the HTML. I still prefer keeping the current implementation, but this certainly would work.

**Comment by quartzmo** [comment]
@callmehiphop Do you have time to do a PR for that right now?

**Comment by blowmage** [comment]
If you move forward with the separate attributes for `type` and `method`, I'd also suggest having a separate attribute for guide content as well.

Guide:

```html
<a data-guide="AUTHENTICATION"></a>
```

Type:

```html
<a data-custom-type="Gcloud"></a>
```

Method:

```html
<a data-custom-type="Gcloud" data-method="#bigquery"></a>
```

**Comment by quartzmo** [comment]
@callmehiphop I don't have much time, so I'm going to start now on a PR that reverts to `?method=` and introduces the new `method` attribute.
