### ISSUE TITLE
Move "Available methods" section from constructor

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-common#114]
In gcloud-ruby, many class constructors are excluded from the docs, which results in services (classes) that do not have an "Available methods" section. [This section is guarded](https://github.com/GoogleCloudPlatform/gcloud-common/blob/master/site/src/app/service/service.html#L40-L45) by: `ng-if="method.isConstructor"`. But can it be displayed for all services? If not, what alternative logic can hide it when appropriate?

**Comment by callmehiphop** [comment]
@quartzmo I think this was resolved via PHP integration, could you verify? https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.35.0/bigquery

**Comment by quartzmo** [comment]
@callmehiphop LGTM, want to close this issue then with a link to the PR that fixed it?

**Comment by callmehiphop** [comment]
@quartzmo sounds perfect, thanks for verifying! 

Closing per #99

**Comment by quartzmo** [comment]
@callmehiphop This is really great for gcloud-ruby, thanks a lot!
