### ISSUE TITLE
/#/docs should go to latest version

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-common#125]
I noticed a link such as:

https://googlecloudplatform.github.io/gcloud-node/#/docs

returns a white page. @callmehiphop could you see if that's a bug or we need another route to redirect that to the latest version?

**Comment by callmehiphop** [comment]
Looks like a bug! Opened #126 to fix it :)

Good catch!

**Comment by stephenplusplus** [comment]
Thanks for the quick fix, sir!
