### ISSUE TITLE
Docs site generated navigation titles

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/gcloud-common#133]
In the docs site there's a convention of `Thing » Subthing`. This looks great, but it might better maintain consistency if it was managed on the site generation side rather than allowing projects to change the convention?

Mentioned: https://github.com/GoogleCloudPlatform/gcloud-python/pull/1775#discussion_r62203856

**Comment by callmehiphop** [comment]
> In the docs site there's a convention of Thing » Subthing

That's actually a Node specific feature. Ruby uses a Namespace (I think)

> This looks great, but it might better maintain consistency if it was managed on the site generation side rather than allowing projects to change the convention?

We actually used to do exactly what JJ was describing, but after consulting both the Ruby and PHP teams, we found that it really only worked out for Node and got pretty hacky for the other languages.

I think if we were to go back to something like this, we would probably have to pass the entire doc object for a given page to a directive and let each language write their own logic for determining the title, I think that would work for everyone? But others would definitely need to chime in there.

/cc @quartzmo @dwsupplee

**Comment by daspecster** [comment]
Ah ok, so in this case for Python it should be more like `thing.subthing`.  I thought it more of a common design language for navigation.

Thanks for the context @callmehiphop!

**Comment by callmehiphop** [comment]
@daspecster currently gcloud-python's docs don't really use any sort of fancy titles, it's literally just the name of the object (as far as I can tell at least)

https://googlecloudplatform.github.io/gcloud-python/stable/storage-batch.html -> `Batches`
https://googlecloudplatform.github.io/gcloud-python/stable/datastore-queries.html -> `Queries`

**Comment by dhermes** [comment]
RE: @callmehiphop comment, those names can be fetched from the Sphinx RST files:

https://github.com/GoogleCloudPlatform/gcloud-python/blob/67693642144dee7d9c336abfe01885c8b54aae0f/docs/storage-batch.rst
https://github.com/GoogleCloudPlatform/gcloud-python/blob/67693642144dee7d9c336abfe01885c8b54aae0f/docs/datastore-queries.rst

**Comment by callmehiphop** [comment]
@dhermes Ahh, my mistake!

**Comment by dhermes** [comment]
No worries. The takeaway here is a positive one, that most of the content is there to automate.

**Comment by daspecster** [comment]
Cool, yeah I'm good to close this if you guys are?
I think the issue was that I didn't realize that the titles were actually representing the namespaces.

**Comment by jgeewax** [comment]
Hang on... isn't the issue that we can't dynamically derive the proper place to separate because that's language specific? If so, I'm not suggesting that we do that... I'm suggesting that we accept a JSON list of the parts, which then could be joined by the special magical character (whatever that might be, here it's "»").

In other words, I'm just saying that we should take the magic special character out of the generation side of things, and add it in at the rendering side...

**Comment by callmehiphop** [comment]
Sure, we can do that.

**Comment by daspecster** [comment]
Just for clarity,
examples...

NodeJs Special character would be ` » `
`Thing  » Subthing  » SubSubthing`

Python Special character would be `.`
`thing.subthing.subsubthing`

Ruby Special character would be `::`
`Thing::Subthing::SubSubthing`

PHP Special character would be `\`
`Thing\Subthing\SubSubthing`

**Comment by jgeewax** [comment]
Sure -- how about we let people set the separating character in the JSON doc and just default it to the » char?

**Comment by jgeewax** [comment]
Whoops - looks like you're a few steps ahead of me -- sorry for the noise!
