### ISSUE TITLE
Can we remove the hashbang to support anchors in URLs?

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-common#136]
We have an issue where we can't link to sections of documentation using an anchor, because the docs are already using the anchor for the hashbang. So this URL doesn't link to the right element on the page:

https://googlecloudplatform.github.io/gcloud-ruby/#/docs/v0.9.0/gcloud/datastore#the-datastore-emulator

Sharing these URLs is super important for a documentation site. Would it be possible to enable [`html5Mode`](https://docs.angularjs.org/guide/$location) in the angular app so the only hash in a URL is for the anchor on the page? If this change was made we could link to the element using this URL instead:

https://googlecloudplatform.github.io/gcloud-ruby/docs/v0.9.0/gcloud/datastore#the-datastore-emulator

Thoughts?

**Comment by stephenplusplus** [comment]
gh-pages doesn't allow `html5Mode`, because we can't instruct the GitHub server to redirect * requests to `index.html`-- usually handled by Apache rewrite conditions or other server logic.

This is why we have to use `?method={methodName}` for deep-linking in that case. We will likely have to come up with another shorthand `?section=the-datastore-emulator` to accomplish the same thing.

@callmehiphop does that sound right?

**Comment by blowmage** [comment]
> we can't instruct the GitHub server to redirect * requests to index.html

I think we can, actually. What if we copied the contents of the `index.html` file to the `404.html` file? That way all the new paths requested to the web server will be responded to with the angular app. Thoughts?

**Comment by stephenplusplus** [comment]
That's got to be one of the top 4 ideas I've heard in my life. @callmehiphop seems like it would work, right?

**Comment by blowmage** [comment]
I wish I could take credit for it...

https://twitter.com/csuwildcat/status/730558238458937344

**Comment by quartzmo** [comment]
Amazing, that tweet was just last night?!

**Comment by blowmage** [comment]
Also, https://twitter.com/csuwildcat/status/730741235472732161

**Comment by callmehiphop** [comment]
That could work, I might try and fiddle around with that this weekend (unless some one else wants to take a stab at it first)

**Comment by blowmage** [comment]
Update on this: http://www.backalleycoder.com/2016/05/13/sghpa-the-single-page-app-hack-for-github-pages/

**Comment by stephenplusplus** [comment]
Hey, how the heck is this working:

https://quartzmo.github.io/gcloud-ruby/#/docs/master/gcloud/datastore#retrieving-records
https://quartzmo.github.io/gcloud-ruby/#/docs/master/gcloud/dns#listing-zones

**Comment by blowmage** [comment]
It doesn't always work.

**Comment by stephenplusplus** [comment]
As in if I refresh that page 100 times, it won't work 100 times? Or it doesn't work with certain links, certain pages, etc?

If it's a race condition, it might be worth fixing it if we thought the hack was too hacky.

**Comment by blowmage** [comment]
I have found that if the app is already loaded in the browser it usually works. But if you follow link from an external site the app won't be loaded and the anchor will not work. I also think both Chrome and Safari behave slightly differently, but I haven't delved deeply into that.

**Comment by callmehiphop** [comment]
Closing per https://github.com/GoogleCloudPlatform/gcloud-common/issues/137#issuecomment-226151297
