### ISSUE TITLE
Site: Request to support examples outside of methods.

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/gcloud-common#140]
For Python, there are times that documentation might be in an `__init__.py` (https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/gcloud/datastore/__init__.py) so there isn't a method to put those into so the output ends up unstyled.

Is there a way that we could support having examples outside of the `methods: []` list?

Also, I could make a fake method to put these in but I don't think that would end up looking right.

**Comment by callmehiphop** [comment]
I think we actually support this. Per https://github.com/GoogleCloudPlatform/gcloud-common/blob/master/site/src/app/service/service.html#L30, I believe you can just do

```
{
  examples: [..],
  methods: [...]
}
```

Want to give that a try and see if it works?

**Comment by daspecster** [comment]
Ahhhh ok I'll give that a go and close this if it it works!  Thanks!
