### ISSUE TITLE
Site supporting multiple classes per .json file or some other solution

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/gcloud-common#145]
For the site navigation it makes sense that modules are essentially the top level navigation structure with
the classes as the subnav and possible the methods below that. (#143).
![screen shot 2016-06-09 at 12 34 53 pm](https://cloud.githubusercontent.com/assets/192456/15937874/a04fdc5c-2e3e-11e6-894c-fce1c5902c42.png)

In Python there is often more than one class per module(file).

Example:
https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/gcloud/connection.py

Sphinx allows you to organize where you want these things to show up.
https://googlecloudplatform.github.io/gcloud-python/stable/gcloud-api.html#gcloud.connection.Connection

```
    Base Connections
    ~~~~~~~~~~~~~~~~

    .. automodule:: gcloud.connection
      :members:
      :show-inheritance:
```
See: https://raw.githubusercontent.com/GoogleCloudPlatform/gcloud-python/master/docs/gcloud-api.rst

After talking to @callmehiphop a little bit, it sounds like supporting a list of `types`/`classes` in the .json files might solve this but I'm sure there are other implications as well.

Example:

```json
[
    {
      "description": "", 
      "id": "gcloud.connection.Connection", 
      "methods": [],
      "name": "Connection", 
      "source": "/gcloud/connection.py"
    },
    {
      "description": "", 
      "id": "gcloud.connection.JSONConnection", 
      "methods": [],
      "name": "JSONConnection", 
      "source": "/gcloud/connection.py"
    }
]
```
Note: another level was added to the `id`. Originally it was just `gcloud.connection`.

**Comment by callmehiphop** [comment]
Is this a feature either the PHP or Ruby teams would also benefit from?

/cc @dwsupplee @quartzmo

**Comment by dwsupplee** [comment]
Not really, the convention in PHP is one file for per class.

**Comment by daspecster** [comment]
@callmehiphop, I haven't found a great way to do this without this change.  I'm open to ideas though!

**Comment by daspecster** [comment]
I'm going to try and just create one json file per python class for now and if we don't like that we can either change how the app treats the nav or figure out a better way to generate the json.

**Comment by quartzmo** [comment]
@callmehiphop, Sorry to comment late, but... Since we produce our JSON from an in-memory tree of code objects, not source files, I don't think we need this at all for gcloud-ruby.
