### ISSUE TITLE
Cloud Pub/Sub went GA

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/gcloud-common#15]
http://googlecloudplatform.blogspot.com/2015/08/Announcing-General-Availability-of-Google-Cloud-Dataflow-and-Cloud-Pub-Sub.html

I think some of the READMEs still say Pub/Sub is beta.
- [x] node
- [x] python (never said beta)
- [x] ruby (never said beta)
- [ ] golang

**Comment by jgeewax** [comment]
/cc @blowmage : Are we good on ruby?

If so, @tmatsuo , can we call this closed?

**Comment by blowmage** [comment]
gcloud-ruby uses the v1 API. I don't Believe we are using the beta label anywhere, but I'll grab the project when I get in front of my computer (~30 minutes).

**Comment by blowmage** [comment]
Confirmed gcloud-ruby isn't labeling Pub/Sub as beta. :+1:

**Comment by jgeewax** [comment]
Cool - checklist looks done... I guess I'll resolve this one. @tmatsuo : Let me know if you still needed something...

**Comment by tmatsuo** [comment]
Thanks!
I forgot to add golang! It still says alpha.

**Comment by okdave** [comment]
There's still an API change we're hoping to make for Go which is why it hasn't been upgraded yet…
@mcgreevy
