### ISSUE TITLE
Support markdown documentation files that aren't listed as Guides

### ISSUE THREAD

**Issue by jdpedrie** [GoogleCloudPlatform/gcloud-common#150]
As some of our documentation moves away from simple inline code comments, we are finding the need to offer documents detailing common arguments, concepts, etc. The docs site currently supports markdown file "guides", but not all of our documentation would rise to that level. Including pages in the docs site that are not linked in the sidebar would be quite useful to us.

**Comment by stephenplusplus** [comment]
Just a thought, wouldn't we still want a link in the sidebar for discoverabilty as well as rediscoverability?

**Comment by jdpedrie** [comment]
It depends on the concept I think. The specific case I am considering here is in-depth documentation for the available arguments in a client constructor. Say when you are creating a PubSubClient or a VisionClient. These arguments will not vary between classes, but there are quite a few of them and the structure needs explanation.

There would be quite a lot of references to this document from different pages in the docs site, so I am not overly concerned about discoverability in this case, and I don't think this page rises to the level of being highlighted in the sidebar.

That said, I do take your point and agree that this is something that should be used sparingly. 👍

**Comment by callmehiphop** [comment]
We parse markdown on the fly on the site already (for certain fields rather), it's just not possible to link to a markdown file. Is there any reason why we couldn't just dump the contents of your markdown file into the JSON via your doc scripts?

**Comment by daspecster** [comment]
I was just talking to @jdpedrie, wouldn't this be possible if it wasn't required that the file was in the TOC? If that requirement is removed then I would think that it would just work?

**Comment by callmehiphop** [comment]
@daspecster I'm not sure I follow, all the toc does is specify what goes in the side navigation. We don't actually specify any of the files to be used for services there.

**Comment by daspecster** [comment]
@jdpedrie was saying that he could make another MD file and place it in the root path but it was only accessible if it was in the TOC. I haven't tried it though.

**Comment by jdpedrie** [comment]
Creating `site/src/json/master/foo.md` and navigating to `http://localhost:3000/#/docs/master/guides/foo` results in a blank white screen. If I add the following to `toc.json` in the `guides` array, the page loads.

```
{
  "title": "foo",
  "id": "foo",
  "edit": "https://github.com/GoogleCloudPlatform/gcloud-common/edit/master/foo.md",
  "contents": [
    "https://raw.githubusercontent.com/GoogleCloudPlatform/gcloud-common/master/foo.md",
    "foo.md"
  ]
}
```

**Comment by jdpedrie** [comment]
I think @callmehiphop's idea of just marking markdown files into json will work fine though.

**Comment by callmehiphop** [comment]
@jdpedrie is this still an issue or do you think we can close it out?

**Comment by jdpedrie** [comment]
We can close it. 😄
