### ISSUE TITLE
gh-pages doc sites are redirecting to cloud.google.com and 404ing

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/gcloud-common#154]
We got a report [here](https://github.com/GoogleCloudPlatform/gcloud-python/issues/2022). Looks like the DNS record was changed.

Seems to be happening to all the gh-pages doc sites.

**Comment by jgeewax** [comment]
Gotcha. Digging now.

**Comment by stephenplusplus** [comment]
They're back!
