### ISSUE TITLE
Look at using Gitlab CI (or Jenkins, or anything else) for our builds?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-common#17]
Right now, Travis is compartmentalized only by our organization (GoogleCloudPlatform) which means that gcloud-* libraries might wait a really long time in the queue to get a build kicked off... 

I got in touch with the Travis folks asking if I could just pay for a few repositories -- which they said no (if I did pay, it'd make the org faster, but... that might not even really fix the problem...)

Is it worthwhile looking at another build configuration that we can share for the gcloud-* libraries?

/cc @dhermes @stephenplusplus

**Comment by jgeewax** [comment]
Gitlab CI: https://about.gitlab.com/gitlab-ci/

**Comment by stephenplusplus** [comment]
I haven't had any trouble with builds not starting right away. I think sticking with Travis is a safe move, as it's become the standard. Are there any other problems we have with Travis that we need to get away from?

**Comment by jgeewax** [comment]
There might be security concerns for Google (can we trust Travis not to fuck with our deployments? or to hold our deployment keys?).

However during the work day I definitely see slow builds for gcloud-python :(

**Comment by blowmage** [comment]
The gcloud-ruby builds are a bit slower during the day on weekdays, but it hasn't blocked us.

**Comment by jgeewax** [comment]
Closing this and taking the conversation over to #32
