### ISSUE TITLE
Doc site "source" param not consistently working?

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/gcloud-common#181]
There seems to be a case where the `source` attribute doesn't seem to get picked up by the doc site.

The anchor for "Source Code" here doesn't have the full href to the file.
https://googlecloudplatform.github.io/gcloud-python/#/docs/master/gcloud/monitoring

The JSON for this can be found here...
https://github.com/GoogleCloudPlatform/gcloud-python/blob/gh-pages/json/master/gcloud/monitoring/index.json#L18

First reported: https://github.com/GoogleCloudPlatform/gcloud-python/issues/2246

**Comment by callmehiphop** [comment]
I believe it's because the app is trying to use a different source field - https://github.com/GoogleCloudPlatform/gcloud-python/blob/gh-pages/json/master/gcloud/monitoring/index.json#L13

**Comment by daspecster** [comment]
Thanks @callmehiphop, it must be some issue in my module generation code then.
