### ISSUE TITLE
Python link in language drop-down sends user to gcloud-python

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-common#194]
_From @omaray on September 30, 2016 0:46_

The language drop-down on the [Client Library Reference page for Node](https://googlecloudplatform.github.io/google-cloud-node/#/) sends users to gcloud-python when selecting Python:

![image](https://cloud.githubusercontent.com/assets/6609430/18977130/930d6f88-866c-11e6-9bd4-10560f442397.png)

It's a problem because sometimes we'll see a 404 appear.

[Expected]
It should point to google-cloud-python.

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#1651_

**Comment by stephenplusplus** [comment]
Nevermind, it does look like it's just Node with the bad link.

**Comment by callmehiphop** [comment]
@stephenplusplus looks like Ruby and PHP are like that as well? Don't forget we added a redirect to googlecloudplatform.github.io, so even though we're sending them to gcloud-python they end up in the right place.

**Comment by stephenplusplus** [comment]
The drop down on https://googlecloudplatform.github.io/google-cloud-python/ points to the correct URL. I'm confused. But if it's resolved, then I'll stop thinking about it :)

**Comment by callmehiphop** [comment]
@stephenplusplus Python stopped using the common app, I believe it is just us, PHP and Ruby at this point.

**Comment by tseaver** [comment]
@callmehiphop We couldn't suss out well enough how to generate the data the app wants, given the way the Sphinx source documentation is arranged.  We have another run at it on the horizon, but needed to have the docs solid, rather than trying to fix them while they are actually deployed.

**Comment by callmehiphop** [comment]
@tseaver totally makes sense!
