### ISSUE TITLE
index.html title is still "gcloud"

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-common#195]
Thanks to @omaray for reporting this in GoogleCloudPlatform/google-cloud-ruby#945.

In the `google-cloud-ruby` gh-pages `index.html`, we changed the `title` to `google-cloud-ruby` some time ago, but the automated doc site update script in `gcloud-common` overwrites `index.html` regularly. You can see that it reverted the title to `gcloud` in [this commit](https://github.com/GoogleCloudPlatform/google-cloud-ruby/commit/2f1ca8164cac7229d70b20200842851fd71cf3df).

A solution for all platforms would be for the deploy script to dynamically set the correct project name (`google-cloud-<platform>`) in the `title` element in [site/src/index.html](https://github.com/GoogleCloudPlatform/gcloud-common/blob/master/site/src/index.html).

**Comment by quartzmo** [comment]
I'm working on a PR for this now. Unless anyone feels very strongly about it, it will just be a build-time solution to replace a generic placeholder in `title` (`google-cloud`) with the value of `moduleName` in `manifest.json` (`google-cloud-ruby`).

**Comment by quartzmo** [comment]
Hmmm, not sure a build time solution will work after all...

**Comment by callmehiphop** [comment]
@quartzmo would just setting the title to google-cloud be sufficient?
