### ISSUE TITLE
question: daily testing

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-common#199]
_From @callmehiphop on October 12, 2016 23:21_

Since we've modularized our library, we've tried to speed up our builds by only testing the modules that have seen code changes. Because of this some modules are getting tested less since they receive fewer updates, I think it would be a good idea to set up a daily [cron job](https://docs.travis-ci.com/user/cron-jobs/) to run system tests for all modules.

Thoughts?

/cc @omaray @jgeewax 

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#1685_

**Comment by stephenplusplus** [comment]
Sounds like a win 👍

**Comment by omaray** [comment]
I don't dislike at all!

**Comment by stephenplusplus** [comment]
Closing in favor of #222
