### ISSUE TITLE
ci: AppVeyor is broken

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-common#215]
_From @callmehiphop on January 3, 2017 20:47_

Looks like our AppVeyor builds are no longer running, we just have a long list of queued jobs.

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#1902_

**Comment by stephenplusplus** [comment]
_From @callmehiphop on January 3, 2017 20:47_

/cc @bjwatson

**Comment by stephenplusplus** [comment]
We're all stalled. Maybe we hit some type of hidden limit and need to upgrade to a paid plan.

// @jgeewax @omaray

**Comment by bjwatson** [comment]
@dhermes @tseaver Are you aware of any reasons why AppVeyor might be stalled like this for google-cloud-node?

**Comment by dhermes** [comment]
Nope. I'd guess it's org throttling, but it's very much a **guess**.

**Comment by tswast** [comment]
I'm an admin for the org on GitHub but I couldn't figure out how to
configure org-wide billing. Appveyor seems like it is per-project.

**Comment by quartzmo** [comment]
Seemingly out of nowhere, Appveyor just delivered a build notification for commit from about 2 weeks ago (google-cloud-ruby):

> [Build google-cloud-ruby 1.0.522 failed](https://ci.appveyor.com/project/GoogleCloudPlatform/google-cloud-ruby/build/1.0.522)
> Commit 7e38bc53cb by Daniel Azuma on 12/21/2016 11:05 PM

**Comment by stephenplusplus** [comment]
I think this has been resolved, at least with GCN. Anyone re-open if they're having issues.
