### ISSUE TITLE
"publishTime" of PubSub emulator is missing millis/nanos

### ISSUE THREAD

**Issue by flunderpero** [GoogleCloudPlatform/gcloud-common#224]
According to the [documentation](https://cloud.google.com/pubsub/docs/reference/rest/v1/PubsubMessage), the field `publishTime` should contain fractions, but the emulator always returns a timestamp with second-precision only:

Here's an example:
```
curl -H "Content-Type: application/json" -X POST -d "{'maxMessages': 10}" http://127.0.0.1:8000/v1/projects/<some project>/subscriptions/<some subscription>:pull

{
  "receivedMessages": [{
    "ackId": "projects/<some project>/subscriptions/<some subscription>:3230735",
    "message": {
      "data": "<message data>",
      "attributes": {
      },
      "messageId": "48",
      "publishTime": "2017-05-15T09:00:50Z"
    }
  },
```

I am using the Python client-API which returns `publishTime` as `Message.service_timestamp` which is a string.

First off, our code relies on the precision of `publishTime` - which I just double-checked is returned with sub-second-precision from real pub-sub - and even worse, we have to implement workarounds because `datetime.strptime("%Y-%m-%dT%H:%M:%S.%fZ", message.service_timestamp)` raises an error when parsing a timestamp w/o sub-second precision.

**Comment by stephenplusplus** [comment]
We only wrap the APIs, so their development isn't tracked here. Please consider one of the channels mentioned [here](https://cloud.google.com/pubsub/docs/support) to report this issue.

**Comment by flunderpero** [comment]
Ah, sorry. Thanks for the link. (I saw other emulator-related issues and thought, this would be the correct place.)
I'm closing this issue.
