### ISSUE TITLE
Make it possible to get back to the landing page?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-common#27]
If I get to the inner page, getting back to the landing page means I have to delete some text in the URL... Kind of annoying.

Can we maybe make the GCP logo (top top left) take us to the landing page, and the "gcloud" text take us to the top level of the inner docs?

![topleft](https://cloud.githubusercontent.com/assets/112928/9550038/003e138a-4d77-11e5-8ab1-5234fce2344d.png)

Who | for language | Vote
---|---|---
@okdave|Go|n/a (no landing page)
@aozarov|Java|n/a (no inner page)
@mziccard|Java|n/a (no inner page)
@stephenplusplus|Node|(Logo to homepage, text to doc landing page)
@callmehiphop|Node| Logo to homepage, text to doc landing page
@dhermes|Python|
@tseaver|Python|
@blowmage|Ruby| Both link to homepage
@quartzmo|Ruby| Logo to homepage, text to doc landing page

**Comment by blowmage** [comment]
In gcloud-ruby the logo and text link back to the landing page. I think this makes the most sense. It doesn't seem obvious to me that the logo and the text would go to different locations.

**Comment by jgeewax** [comment]
Ah yes, you guys have that Overview page that's the landing page, so this is less of an issue.

**Comment by quartzmo** [comment]
I might be missing something, but I don't see much issue for Ruby or Node. I do see it for Python.

**Comment by blowmage** [comment]
Ah, by "landing page" you mean the main documentation page, not the site homepage. My mistake.

**Comment by dhermes** [comment]
I'm happy to add the link or anything else you add but have a question:

Why does a user ever want to go back to the landing page?

It's **very** pretty but doesn't say much about using the library. Once their in the docs, they are in the place they meant to go to.

**Comment by callmehiphop** [comment]
I'm ok with this idea. To me the line between the logo and *gcloud* text denotes that they already are separate entities, so I find it weird that together they create a single link.

**Comment by quartzmo** [comment]
I agree with @callmehiphop about that line implying two different links.

**Comment by jgeewax** [comment]
@dhermes : I totally agreed with you, until I just saw someone struggle:

> "I just saw that nice datastore example, I wanted to try that... wait... what... where... how the hell do I get back to that... ? Do I really have to click back 7 times?"

**Comment by aozarov** [comment]
I think for Java we should explore the option of adding a customized header to the Maven generated site that will include the navigation bar.

We may be able to do something for the Javadoc as well but without a separate Frame I doubt the flexibility we have for it.

@ajkannan ?

**Comment by ajkannan** [comment]
I can look into adding a navigation bar for the Maven generated site for gcloud-java.  I agree that the Javadoc site may be a bit more tricky.

**Comment by dhermes** [comment]
Has anyone implemented this yet?
