### ISSUE TITLE
docs: handle custom docs

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-common#43]
Our docs template can pull in our gcloud-common markdown files (the ones that live in this repo, such as Authentication, Troubleshooting, etc). Will we be able to support loading custom documents, and if so, how will our libraries be able to do that?

**Comment by quartzmo** [comment]
What about the common design pattern of letting clients override default "shipped" templates by creating files (in a local directory) with the same filepath. (Example: Wordpress templates.)

So, the Angular app would have a master list of all possible files, and would also have default documents to use where applicable.

```sh
authentication/readme.md # if found in client's overrides dir, use that, otherwise use common
getting_started/readme.md # if found in client's overrides dir, use that, otherwise omit from menu, since not in common
```

**Comment by stephenplusplus** [comment]
That's a good idea, but I wonder if it would be better to "append to" instead of override. We do this in Node for our custom instructions on how to auth with our library. (The `With gcloud-node` section [here](https://googlecloudplatform.github.io/gcloud-node/#/authentication))

I'm also hoping to solve allowing each library can have additional, unique sections.

**Comment by quartzmo** [comment]
It can still done with templates and overrides, which I think is easier to understand than appending. If `authentication/readme.md` *includes* a template named `authentication/additional.md` near its end (blank by default), the client can "override" to replace the default (blank) content with more info.

**Comment by quartzmo** [comment]
Actually, rather than being potentially easier to understand, the override approach allows more flexibility, because clients can choose at which level to replace defaults with their own content.

**Comment by stephenplusplus** [comment]
Good thinking, I like it!

**Comment by callmehiphop** [comment]
What about custom pages? Python has a page dedicated to [shared core modules](http://googlecloudplatform.github.io/gcloud-python/stable/gcloud-api.html), would that go away or get lumped in elsewhere? I think our solution should probably offer the flexibility to support ad hoc pages

**Comment by stephenplusplus** [comment]
Is that this: https://github.com/GoogleCloudPlatform/gcloud-common/issues/43 ?

**Comment by callmehiphop** [comment]
> Is that this: #43 ?

Yes? You linked to this issue, did you mean to link to a different one?

In case my wording was confusing - what if we wanted to add a node specific link to our Getting Started list of links, how would we do that without it ending up on Ruby's version?

**Comment by stephenplusplus** [comment]
Updated my comment :)

**Comment by callmehiphop** [comment]
Gotcha, thanks!

The summary of this issue says

> Will we be able to support loading custom documents, and if so, how will our libraries be able to do that?

I assumed it was related to this issue based off of that verbiage, but I see now that this issue is about including custom content on pages that are based off of gcloud-common markdown files, my bad!

**Comment by stephenplusplus** [comment]
That's actually not what I meant it to be about. Words are not my friend lately.

Really the only thing this issue is for is what you are describing... custom pages for each of our docs. We talked about how to override and extend the gcloud-common docs, but that's just one part of the problem.

To get the discussion back to "how should we all host/define custom pages?", do you have any ideas?

**Comment by callmehiphop** [comment]
I like the overriding idea @quartzmo suggested, it sounds flexible and fairly easy to implement. Although if we're going to have markdown files live locally to serve as overrides, we could just as easily do HTML and use the table of contents JSON to specify our local HTML files. That might simplify things a bit since we'd no longer check to see if content was being overridden in order to determine whether or not we should display the default file.

**Comment by stephenplusplus** [comment]
Re MD vs HTML, MD is preferred for ease of contribution.

**Comment by callmehiphop** [comment]
I'm not really saying abandon MD, but obviously at some point HTML needs to exist - since this is an Angular application, I'm assuming we'll use a directive to load the markdown file. I'm suggesting providing a template that contains the usage of said directive to specify which markdown files are included and their position in the document.

**Comment by stephenplusplus** [comment]
It might just be the weekend getting the best of me, but that's a little blurry to me. Can you whip up some type of sample of the basics of that architecture?

**Comment by callmehiphop** [comment]
Basically it all stays the same, you have a JSON file that points to a file containing content, but instead of a MD file it's an HTML file. Inside the HTML file it looks something like

```html
<markdown-directive src="https://raw.githubusercontent.com/GoogleCloudPlatform/gcloud-common/master/authentication/readme.md" />
<markdown-directive src="/local/markdown.md" />
```

**Comment by stephenplusplus** [comment]
Brilliant!

**Comment by callmehiphop** [comment]
This got brought up last week, but we may need to somehow version the language specific markdown files.The reasoning is that if something like authentication were to change and a user was using an older version of the client, as it is today, they would be presented with newer authentication steps without the ability to the steps specific to their version.
