### ISSUE TITLE
docs: landing page

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-common#44]
Each of our landing pages are distinct, including different descriptions, examples, and getting started instructions. In our generic docs template, can we support all of these being customized without duplicating templates/styles, etc?

**Comment by callmehiphop** [comment]
They look similar enough to me that I think we could create a JSON schema for a landing page

**Comment by dhermes** [comment]
@stephenplusplus We styled ours after `node` and the only reason it may be different is bit rot

**Comment by callmehiphop** [comment]
I think they're similar enough to create a re-usable template for this. The bigger question is where do we store all the content that goes into the homepage?

My vote goes to plop it in some JSON.

**Comment by stephenplusplus** [comment]
Is something more Angular-extensible possible, like using directives to just open windows where text will go and such? If I'm a person browsing the docs and catch a typo, I'll be really confused and probably give up if I've gotta dig through JSON.

**Comment by callmehiphop** [comment]
I don't really see many good options for this.

Markdown doesn't seem flexible enough to accommodate specific elements on the home page (columns, tabs, etc.) Unless we wanted to maintain a slew of markdown files for a single page (kinda bleh)

Using HTML runs the risk of certain languages going stale when updates occur, which is whole reason we're doing this in the first place.

We could let each app create an angular specific file (controller, provider, etc.) that had all the data we need already bound to it, but I see this being equally as tedious to maintain as JSON.

I realize JSON is lame for this, but it offers us the flexibility we need and allows for updates to be made to the angular application without needing updates to the documentation, which is why I suggest it.

**Comment by stephenplusplus** [comment]
> Using HTML runs the risk of certain languages going stale when updates occur

Our landing page isn't versioned, and I would say it doesn't have to be. It's to reflect where we're at now, more as a marketing/"ooh, so easy!" device.

> allows for updates to be made to the angular application without needing updates to the documentation

What do you mean?

Maybe Angular directives are too extreme and good-ol HTML + CSS can do the job:

```html
<pre class="example">
code
</pre>

<ul class="resource-links">
  <li><a href="http://github.com/googlecloud..."><img /></a></li>
</ul>

<dl class="faq">
  <dt>What is gcloud?</dt>
  <dd>gcloud is...</dd>
</dl>
```

**Comment by callmehiphop** [comment]
> Our landing page isn't versioned, and I would say it doesn't have to be. It's to reflect where we're at now, more as a marketing/"ooh, so easy!" device.

I'm not really talking about versioning, I'm mostly talking about styling inconsistencies from language to language, in regards to the homepage specifically these inconsistencies are very minor but I think we should be aiming to keep them aligned as much as possible.

Sharing a template is going to ensure that all the elements are styled correctly and if later on down the line we decide to update certain areas of the page, we won't have to open an issue on all the various `gcloud-*` repos for them to update their page.

A lot of the content on the homepage is written to be pretty generic, so I don't think we'd even need a whole lot of JSON to cover each page.. here's what I'm thinking

```js
{
  "lang": "node",
  "friendlyLang": "Node.js",
  "google-apis-client": "https://github.com/google/google-api-nodejs-client",
  "description": "Google Cloud Client Library for Node.js - an idiomatic, intuitive, and natural way for Node.js developers to integrate with Google Cloud Platform services, like Cloud Datastore and Cloud Storage.",
  "icon": "assets/images/icon-lang-nodejs.svg",
  "versions": ["master"],
  "package": {
    "name": "npm",
    "url": "https://www.npmjs.com/package/gcloud",
    "example": "<code class=\"subtle--blue\">$</code> npm install <code class=\"subtle--blue\">--save</code> <strong>gcloud</strong>"
  },
  "about": {
    "description": "Upload a file to Cloud Storage",
    "examples": [{
      "title": "Run in Compute Engine",
      "code": "// Authentication is automatic\n// inside Google Compute Engine.\nvar gcloud = require('gcloud')({\n\tprojectId: 'grape-spaceship-123'\n});\n\nvar gcs = gcloud.storage();\n\nvar backups = gcs.bucket('backups');\nbackups.upload('db.zip', function(err, file) {\n\t// file.createReadStream();\n\t// file.getMetadata();\n\t// ...\n});"
    }, {
      "title": "Run elsewhere",
      "code": "var gcloud = require('gcloud')({\n\tprojectId: 'grape-spaceship-123',\n\t// Specify a path to a keyfile.\n\tkeyFilename: '/path/to/keyfile.json'\n});\n\nvar gcs = gcloud.storage();\n\nvar backups = gcs.bucket('backups');\nbackups.upload('db.zip', function(err, file) {\n\t// file.createReadStream();\n\t// file.getMetadata();\n\t// ...\n});"
    }]
  },
  "examples": [{
    "title": "Getting Started with Compute Engine and Node.js",
    "href": "https://cloud.google.com/nodejs",
    "source": "ttps://github.com/GoogleCloudPlatform/nodejs-getting-started",
    "description": "A tutorial for building a web application on Google Cloud Platform."
  }, {
    "title": "TodoMVC",
    "href": "http://gcloud-todos.appspot.com",
    "source": "https://github.com/GoogleCloudPlatform/gcloud-node-todos",
    "description": "TodoMVC backend using gcloud-node and Express."
  }, {
    "title": "gcloud-kvstore",
    "href": "https://github.com/stephenplusplus/gcloud-kvstore",
    "description": "Use a gcloud-node dataset as a Key/Value store."
  }, {
    "title": "gitnpm",
    "href": "http://gitnpm.com/",
    "source": "https://github.com/stephenplusplus/gitnpm",
    "description": "Easily lookup an npm package's GitHub repo using gcloud-node and Google App Engine."
  }]
}

```

**Comment by stephenplusplus** [comment]
I look at that sample and it bums me out :disappointed: 

> I'm mostly talking about styling inconsistencies from language to language, in regards to the homepage specifically these inconsistencies are very minor but I think we should be aiming to keep them aligned as much as possible.

That's what I'm trying to solve as well with CSS. Maybe Angular directives would help close the gap for inconsistencies, such as a `header` directive. But the landing page isn't too complicatedly structured to begin with.

But, whatever you feel is best. If you feel good about JSON, then I'm :+1:

**Comment by callmehiphop** [comment]
How would you layout the landing page with directives? I have a couple ideas but the feel a little verbose..?

**Comment by stephenplusplus** [comment]
This is just an idea...

```html
<div header>
  <p>
    Google Cloud Client Library for Node.js - an idiomatic, intuitive, and natural way for Node.js developers to integrate with Google Cloud Platform services, like Cloud Datastore and Cloud Storage.
  </p>
  <pre example class="hljs hljs-bash">
$ npm install --save gcloud
  </pre>
</div>

<section>
  <button docs>
    Read the Docs
  </button>
  <ul class="external-links">
    <li><a href="..."><img src="" /></a></li>
  </ul>
</section>

<section>
  <h1>What is it?</h1>
  <p>
    gcloud is a client library for accessing Google Cloud Platform services that significantly reduces the boilerplate code you have to write. The library provides high-level API abstractions so they're easier to understand. It embraces idioms of Node.js, works well with the standard library, and integrates better with your codebase. All this means you spend more time creating code that matters to you.
  </p>
  <p>
    gcloud is configured to access Google Cloud Platform services and authenticate (OAuth 2.0) automatically on your behalf. With a one-line install and a private key, you are up and ready to go. Better yet, if you are running on a Google Compute Engine instance, the one-line install is enough!
  </p>
  <pre example title="Upload a file to Cloud Storage">
    ... (we use tabs here, maybe that's not everyone)
  </pre>
</section>

<section>
  <h1>Examples</h1>
  <ul>
    <li><a href="...">Getting Started with Compute Engine and Node.js</a></li>
  </ul>
</section>

<section>
  <h1>FAQ</h1>
  <dl>
    <dt>
      What is the relationship between the gcloud package and the gcloud command-line tool?
    </dt>
    <dd>
      Both the gcloud command-line tool and gcloud package are a part of the Google Cloud SDK: a collection of tools and libraries that enable you to easily create and manage resources on the Google Cloud Platform. The gcloud command-line tool can be used to manage both your development workflow and your Google Cloud Platform resources while the gcloud package is the Google Cloud Client Library for Node.js.
    </dd>
  </dl>
</section>
```

**Comment by callmehiphop** [comment]
That could work, it just seems fragile to me. I could see trying to target elements via tag selectors getting a bit messy and any structural changes to the HTML would have to be replicated in each repo (e.g. we decide the examples section needs to be at the end)

**Comment by stephenplusplus** [comment]
> I could see trying to target elements via tag selectors

We can always put a class on them. With `section`, I was just thinking each one would get a slightly different shade of gray to match the current site. That's the only reason for distinction. The container here can select the children to have that effect. Similar to an alternating color scheme in a table in terms of each row not needing to have a class to say "white" and "gray", I think this falls within fair use of immediate-child tag styling.

>  any structural changes to the HTML would have to be replicated in each repo

This is for sure the cost of this approach, but I'd rather pay this price than asking contributors to deal with JSON (and dealing with it ourselves). I don't see the structural changes being a frequent occurrence. It might even be nicer this way, as each language can customize the page-- in terms of unique use cases, not style changes.
