### ISSUE TITLE
docs: linking to custom types

### ISSUE THREAD

**Issue by callmehiphop** [GoogleCloudPlatform/gcloud-common#46]
I think one of the trickier things we still need to solve is linking to custom types. As it is today we denote custom types with special syntax (e.g. `{module:bigquery#query}`) in [our JSDoc](https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/lib/bigquery/index.js#L116). This has worked well for us, but I don't think it's something that's going to transition to other languages very well, so I believe we need to come up with a new way of accomplishing this.

My initial thought is to just modify the `returns` array to look something like this (although I have no idea what the effort would be to implement this in python/ruby/php/etc.)

```javascript
{
  "returns": [{
    "types": [
      // use a string for plain built in types..
      "string",
      // and object notation for custom types
      {
        "service": "bigquery",
        "page": "table" // page would be optional?
      }
    ]
  }]
}
```

Thoughts?

**Comment by quartzmo** [comment]
Our current Ruby documentation tool auto-generates links to custom types it finds anywhere in the docs. 

For example:

```ruby
    # A Job subclass representing a copy operation that may be performed on a
    # Table. A CopyJob instance is created when you call Table#copy.
```

is rendered as

```html
<p>
A <a href="Job.html">Job</a> subclass representing a copy operation that
may be performed on a <a href="Table.html">Table</a>. A <a href="CopyJob.html">CopyJob</a> 
instance is created when you call <a href="Table.html#method-i-copy">Gcloud::Bigquery::Table#copy</a>.
</p>
```

This is a really awesome usability feature. I think we could support it with language-specific custom type detection in the Angular app. I really don't think it's so bad if at a few points in the app, language-specific strategies are used.

**Comment by quartzmo** [comment]
In addition, being able to use Ruby (e.g. `Gcloud::Bigquery::CopyJob#create_if_needed?`) for our custom type references will save us A LOT of trouble in our docs migration, and will also keep the references readable for people who read the docs directly in the code (very common).

**Comment by blowmage** [comment]
I have some thoughts on this. FWIW. IMHO. YMMV. etc...

I think we should output HTML. I see no reason why we should output any other format, like Markdown. For the links to other code entities I think we should do one of the following:

1) Have an empty `href` but use a `data-` attribute to link to the unique identifier for the entity. e.g. `<a href="" data-resource="Gcloud::Bigquery::CopyJob#create_if_needed?">#create_if_needed?</a>`
2) Have an `href` that uses a custom protocol to link to the unique identifier for the entity.  e.g. `<a href="jsdoc:Gcloud::Bigquery::CopyJob#create_if_needed?">#create_if_needed?</a>`

**Comment by blowmage** [comment]
The assumption I'm making here is that each entity, (module, class, method, function, constant, etc.) has a unique identifier. I would like to control what this is. In ruby an instance method is commonly formatted as `Gcloud::Bigquery::CopyJob#create_if_needed?`, but a class method is `Gcloud::Bigquery::CopyJob.new`. I would really, really like to be able to define this so we can keep ruby things rubyish, but allow node things to be nodeish, and python things pythonish (pythonic?).

**Comment by callmehiphop** [comment]
> Have an empty href but use a data- attribute to link to the unique identifier for the entity. e.g. <a href="" data-resource="Gcloud::Bigquery::CopyJob#create_if_needed?">#create_if_needed?</a>

I love this idea! I think rather than using a data attribute, maybe we could use an Angular directive? This would make it easier to convert the value into an href.

So something like

```html
<a custom-type="Gcloud::Bigquery::CopyJob#create_if_needed?">#create_if_needed?</a>
```

**Comment by quartzmo** [comment]
@callmehiphop So you think there can be an Angular directive that capable of resolving internal URLs from language-native references such as `Gcloud::Bigquery::CopyJob#create_if_needed?` ?

**Comment by callmehiphop** [comment]
@quartzmo yep! I mean I don't see why not, that or we could make a directive per language?
