### ISSUE TITLE
docs: individual module version management

### ISSUE THREAD

**Issue by callmehiphop** [GoogleCloudPlatform/gcloud-common#52]
It seems like there's been a bit of chatter about some libraries moving toward individual modules instead of a single giant module. @blowmage [made a good point](https://github.com/GoogleCloudPlatform/gcloud-common/issues/49#issuecomment-173008535) about how versioning the individual modules will complicate the docs app.

The simplest way to solve that problem (that I can think of) might be to include a menu that simply allows one to switch between the main gcloud module and all individual modules. I put together a quick comp to illustrate the idea (forgive me if it's hideous).

![default-state](https://cloud.githubusercontent.com/assets/1707267/12460380/6b3884e6-bf81-11e5-9350-098a13d1ca36.jpg)
![expanded-state](https://cloud.githubusercontent.com/assets/1707267/12460387/71606cc6-bf81-11e5-914a-c4679e081df3.jpg)

Switching modules could repopulate the version dropdown to only contain the available versions for the selected module. The API section would probably only be populated with relating pages, for example, when selecting gcloud-bigquery, only Dataset, Job and Table would be listed.

Thoughts?

**Comment by dhermes** [comment]
I like it. I assume the `API` sections will change if that menu is implemented?

**Comment by callmehiphop** [comment]
@dhermes yep, that's the idea

**Comment by stephenplusplus** [comment]
If we go this route, this should work. This probably isn't the right place for my comments on the modularization idea (#91 has lots of those!), but here might be the right place to just comment on the complexity this introduces to the user who is brand new to our library.

Imagine you just landed on this page for the first time as...

1. Someone who doesn't know anything about GCP in general, but is going to try out a few of the APIs
2. Someone not using any of our modules currently who only wants GCS access
3. Someone who already uses `gcloud` and wants information about using BigTable

...

For 1, they're going to be confused about using the dropdown vs browsing the API navigation to learn more about the services. It's not clear the dropdown is referencing unique modules, so they might end up installing `gcloud` AND `gcloud-storage`, unsure of which "Getting Started" guide applies to them.

For 2 & 3, our docs site ends up with multiple places for docs that look very similar, but are describing different modules. For example, I might get a link from someone (or end up there on my own by incorrectly using our docs site) that takes me to the gcloud-storage docs. They seem helpful at first glance (judging by the URL, the branding, etc), but they're actually referencing a separate module that I'm not using. If any extra overview/doc materials are given, that's only going to complicate things even more.

Overall, I think this turns our docs sites into apps that must be learned. And usually people at a docs site are already impatient :\

**Comment by callmehiphop** [comment]
Bumping this since it looks to be on the horizon! Having not really looked at this for a while, I had a second thought. 

![module-switcher](https://cloud.githubusercontent.com/assets/1707267/15945233/60c74194-2e5f-11e6-9590-0de674e40ec7.jpg)

WDYT?

/cc @quartzmo @stephenplusplus @dwsupplee @daspecster

**Comment by stephenplusplus** [comment]
Awesome. I think that moving it higher more clearly separates that what they are clicking isn't part of the active page.

**Comment by quartzmo** [comment]
@callmehiphop My understanding per your [comment](https://github.com/GoogleCloudPlatform/gcloud-node/pull/1431#issuecomment-234041418) and @stephenplusplus's reply on GoogleCloudPlatform/gcloud-node#1431 is that you are waiting for acceptance of that PR *before* you begin work on changes to the site app, is that correct? gcloud-ruby is also almost ready to move to multiple packages, and then will need docs support very quickly as well. Please comment here when you actually begin work on the site, and if there's anything we can do to help!

/cc @blowmage

**Comment by callmehiphop** [comment]
Actually no! I've already started on this, need to do a couple things still but it's pretty much wrapped up. I'll open the PR so we can discuss the JSON changes

**Comment by blowmage** [comment]
I shared some thoughts on the UI for the individual package documentation on GoogleCloudPlatform/gcloud-common#159.
