### ISSUE TITLE
Add documentation about our documentation build process

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-common#54]
I think it would be helpful to have a description of the way docs are built and how each place (gcloud-common + gcloud-\*) plays a role in the process as well as what a gcloud-\* library has to do to be compliant. Maybe not anything extensive (@callmehiphop you've got a lot going on!), but just something that answers some obvious questions.

**Comment by callmehiphop** [comment]
+1

**Comment by jgeewax** [comment]
![we-need-to-go-deeper](https://cloud.githubusercontent.com/assets/112928/12726971/8c73b5a2-c8e8-11e5-8d4b-3597a51f9f5a.jpg)

**Comment by dhermes** [comment]
:+1: on the meme

**Comment by stephenplusplus** [comment]
![onthememe](https://cloud.githubusercontent.com/assets/723048/12727253/1c4e6158-c8ea-11e5-87dc-627447778074.png)

**Comment by jgeewax** [comment]
And @stephenplusplus wins.
