### ISSUE TITLE
Split Manifest JSON

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-common#77]
Currently there is a single manifest for all versions and navigation. It would be much simpler for gcloud-ruby if there were separate manifests for each version. We would like to see a main manifest that lists versions, and a version manifest that lists the navigation for the version.

One of the reasons for this request is due to how the `implemented` feature works in the current manifest. Services list which version they are added. This becomes complicated in some common scenarios, such as adding a new construct to master when it isn't released in a version yet. The easiest approach is to maintain this file by hand, but we would prefer to automate it. We could automate the main mainifest, but it would require doing a comparison of every version's navigation. So we either have to maintain a version specific navigation for comparison during mainifest creation, or have the angular app use a version manifest JSON. We think changing the angular app will be simpler and less error prone.

**Comment by callmehiphop** [comment]
:+1:
