### ISSUE TITLE
Separate Code Data from Navigation

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-common#78]
The current services data structure performs double duty. First, it defines the navigation structure, and second it defines the code constructs that are to be documented. These are two different things, and we would like to suggest that they be separated and replaced with two different data structures.

In gcloud-ruby we have many more code constructs (classes, modules) than gcloud-node. Because of this we do not list all of the code constructs in the navigation, prefering to show only the most important constructs. Unfortunately the current angular app is unable to render a code construct's information unless it is also listed in the navigation. This is a problem for us.

Another reason to split these two structures is that for gcloud-ruby's case, and we suspect for other languages, the navigation items listed does not match the namespace structure of our code. We would prefer a structure that more closely resembles the code constructs, and a separate structure to define how the code constructs are to be navigated.

**Comment by stephenplusplus** [comment]
:+1: 

Can you give an example of what the ideal nav bar would look like for your lib. As a template, here's our current one:

```
Getting Started
> Authentication
> FAQ
> Troubleshooting
> Contributing

API
> gcloud
> BigQuery
  > Dataset
  > Table
  > Job
> Compute
> DNS
...

> GitHub
> Issues
> StackOverflow
> [Package Manager]
```

**Comment by blowmage** [comment]
It would look like our [current navigation](http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.6.1/).

**Comment by blowmage** [comment]
We use [this config file](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/yard-gcloud/config/side.yaml) to control the side nav when generating our docs.

**Comment by quartzmo** [comment]
Just to clarify, this issue is about making all code types available in the Angular app, so that they may be linked from the headline types that are listed in the navigation.

**Comment by callmehiphop** [comment]
:+1:

**Comment by quartzmo** [comment]
@callmehiphop @stephenplusplus Just want to bump this issue, as it is our No. 1 blocker for deploying the gcloud-common site to the gcloud-ruby gh-pages. Until the Angular app supports listing/loading additional code types that **do not** appear in the nav, many of our internal links are broken and important documentation is unreachable. (Click the `CopyJob` linked in the description of [BigQuery::Job](http://quartzmo.github.io/gcloud-ruby/#/docs/v0.6.1/bigquery/job) for an example.)

**Comment by callmehiphop** [comment]
@quartzmo I'm going to make this my number 1 priority, starting.. now!

**Comment by quartzmo** [comment]
@callmehiphop Nice! We are closing in on a release, it will be great to deploy our new docs with the site!

**Comment by quartzmo** [comment]
@callmehiphop What do you think, could the site simply load all available JSON files, no matter how deeply nested, making links navigable to any relative path that has a JSON file? We might need to enforce version availability.

**Comment by callmehiphop** [comment]
When I first realized this was an issue for ruby, I was going to suggest adding an optional key to the manifest that prevented an item from showing up in the navigation, but still letting the app know it existed.

We *could* load all the JSON up front, but we were kind of already doing that with the single file approach (that we decided to move away from). Since that time @stephenplusplus has pointed out that we've seen performance gains when compared to the previous gcloud-node site. That being said, I think maybe we should avoid loading them all up front.

A simpler approach could be to just map the state params to a file.. for example if we saw `/docs/v0.28.0/storage/bucket/error` we could then make a network request to `/versions/v0.28.0/storage/bucket/error.json`? If the file doesn't exist, we'd catch the HTTP error and just redirect the user?

**Comment by quartzmo** [comment]
I'll give this approach a try locally right now!

**Comment by blowmage** [comment]
I don't like the idea of loading _all_ the JSON files up front either, and I don't think that is a requirement to separating the navigation from the code constructs documented in the app. But I do think there is a very _strong_ argument to be made for making the app aware of all the code constructs and methods up front in the version manifest. Instant search is just one benefit for this approach, but there will be others.

I would argue that the version manifest JSON provides a _controlled_ redundancy of the code constructs and methods fully documented in the code construct JSON. This redundancy allows for the app to provide all the documentation while maintaining performance.

**Comment by quartzmo** [comment]
@blowmage Sounds good, I don't see any reason to *not* list all code types in the manifest .

**Comment by blowmage** [comment]
In my gist each code construct [provided the url that the JSON was at](https://gist.github.com/blowmage/13be352f40ee7ac5ee48#file-version-json-L102), so each project could organize all their code construct files as they want, instead of following any particular naming convention for those files.

**Comment by quartzmo** [comment]
#97 was supposed to ref this issue, but not close it. Reopening.
