### ISSUE TITLE
Add Unique ID to Guides, Code Constructs, and Methods

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-common#79]
The current angular app displays three main entities, a guide, code construct, and a code method. The routing rules to link to any of these entities with the `data-custom-type` attribute can get complicated quickly. We would prefer that each entity has a unique ID, and that the URL routing and `data-custom-type` attributes use this ID.

**Comment by quartzmo** [comment]
One motivation behind this idea is to facilitate linking to deeply nested code types that are not listed in the navigation. #78 is therefore likely to be a prerequisite.

**Comment by blowmage** [comment]
Agreed. :+1:

**Comment by callmehiphop** [comment]
:+1:

**Comment by callmehiphop** [comment]
Closed by #109 and #115
