### ISSUE TITLE
Add support for redirecting to external docs from version switcher

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-common#90]
In gcloud-ruby, we need to be able to link to old (external) docs from version switcher, since we can't produce JSON docs from older versions.

@callmehiphop Any ideas about how to do this one? I guess we need to expand the manifest JSON to allow some versions to map to external URLs? And add logic in DocsCtrl#loadVersion to handle such versions with redirection the mapped URL? Awkward, right? Any better idea?

(This issue was extracted from PR #65)

**Comment by quartzmo** [comment]
@callmehiphop I think we might need a `site` label for issues such as this one, do you agree? (Some older issues prepend `site:` in the title, but using labels is a better approach if we can make a new one.)

**Comment by callmehiphop** [comment]
@quartzmo that's where my head was at. I think regardless of what we do, we're going to have to extend the manifest to include redirect data. We might be able to contain it within the routing logic however, perhaps by tapping into the `$stateChangeStart` event? We would just have to match the url against any redirects listed in the manifest? 

Good call on the site label :+1:

**Comment by blowmage** [comment]
I figured we just weren't going to list the version pre-YARD.

**Comment by callmehiphop** [comment]
Would it make more sense to include some text underneath the version switcher that said something like *Looking for an older version? Check the legacy docs.* Or something, similar.. allowing the user to link to the old site..?

**Comment by quartzmo** [comment]
@jgeewax Any opinion on the user experience for navigating to older docs? (Including the option of simply not listing gcloud-ruby's pre-YARD (pre-0.7.0 Logging) docs?)

**Comment by callmehiphop** [comment]
@jgeewax do we know if Python is going to need similar functionality or can older versions of the docs be transformed into JSON?

**Comment by jgeewax** [comment]
@dhermes @tseaver

**Comment by dhermes** [comment]
Our docs have been Sphinx docs from day 1, so we can always go back and re-generate.

**Comment by quartzmo** [comment]
We decided simply not to link to older docs in the version switcher. Closing.
