### ISSUE TITLE
customType directive links to wrong version

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-common#92]
Steps to reproduce:

1. Navigate to a view for any library version other than the "current" one. Example: [/#/docs/v0.27.0/bigquery/dataset](https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.27.0/bigquery/dataset)

1. Click an internal link. Example `bigquery#createDataset`.

    Page displayed is for the current version of the library, not the version for the previous view. Example: [/#/docs/v0.28.0/bigquery?method=createDataset](https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.28.0/bigquery?method=createDataset).

**Comment by callmehiphop** [comment]
Ahh, good catch @quartzmo!
